# 貸し会議室サービス - AWS Infrastructure
# Generated by MCL Product Design Skill

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {
    # Configure backend in terraform.tfvars or via CLI
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = "kashikaigishitsu"
      Environment = var.environment
      ManagedBy   = "terraform"
    }
  }
}

# --- Variables ---

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "ap-northeast-1"
}

variable "environment" {
  description = "Environment name (dev/staging/prod)"
  type        = string
  default     = "prod"
}

variable "vpc_cidr" {
  description = "VPC CIDR block"
  type        = string
  default     = "10.0.0.0/16"
}

# --- Modules ---

module "vpc" {
  source = "./modules/vpc"

  vpc_cidr           = var.vpc_cidr
  environment        = var.environment
  availability_zones = 2
}

module "waf" {
  source = "./modules/waf"

  environment = var.environment
}

module "cognito" {
  source = "./modules/cognito"

  environment = var.environment
}

module "rds" {
  source = "./modules/rds"

  environment        = var.environment
  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_data_subnet_ids
  instance_class     = "db.r6g.large"
  engine_version     = "16"
  multi_az           = true
}

module "elasticache" {
  source = "./modules/elasticache"

  environment        = var.environment
  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_data_subnet_ids
  node_type          = "cache.r6g.large"
}

module "sqs" {
  source = "./modules/sqs"

  environment = var.environment
}

module "ecs_cluster" {
  source = "./modules/ecs-cluster"

  environment = var.environment
}

module "ecs_api" {
  source = "./modules/ecs-service"

  environment        = var.environment
  cluster_id         = module.ecs_cluster.cluster_id
  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_app_subnet_ids
  service_name       = "api"
  cpu                = 512
  memory             = 1024
  desired_count      = 2
  min_capacity       = 2
  max_capacity       = 6
}

module "ecs_worker" {
  source = "./modules/ecs-worker"

  environment        = var.environment
  cluster_id         = module.ecs_cluster.cluster_id
  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_app_subnet_ids
  sqs_queue_arn      = module.sqs.queue_arn
}

module "api_gateway" {
  source = "./modules/api-gateway"

  environment      = var.environment
  vpc_link_subnets = module.vpc.private_app_subnet_ids
  cognito_arn      = module.cognito.user_pool_arn
  waf_acl_arn      = module.waf.web_acl_arn
}

module "cloudfront" {
  source = "./modules/cloudfront"

  environment = var.environment
  waf_acl_arn = module.waf.web_acl_arn
}
